package net.openan.a2at.sdk.corpus;

/**
 * The prompt input of one validate-family corpus record.
 *
 * <p>Exactly one variant applies per record: a golden fixture name resolved per language by the engine, an inline
 * prompt text, or the number of the scenario step whose generated prompt text feeds this validation step.
 *
 * @since 2026-08
 */
public sealed interface PromptSource {

    /**
     * The prompt is the golden fixture of the given name, resolved per language.
     *
     * @param golden golden fixture name such as {@code information_propose}
     */
    record Golden(String golden) implements PromptSource {}

    /**
     * The prompt is the given inline text.
     *
     * @param text prompt text verbatim
     */
    record Text(String text) implements PromptSource {}

    /**
     * The prompt is the prompt text generated by an earlier scenario step.
     *
     * @param step number of the producing scenario step, at least 1
     */
    record FromStep(int step) implements PromptSource {}
}
